openapi: 3.0.3
info:
  title: Hackathon Todo API
  description: Multi-user task management API with JWT authentication
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.hackathon-todo.com
    description: Production server

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from Better Auth login

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          example: 1
          description: Unique task identifier
        user_id:
          type: string
          example: "clx1234567890"
          description: ID of the user who owns this task
        title:
          type: string
          maxLength: 200
          minLength: 1
          example: "Buy groceries"
          description: Task title (required)
        description:
          type: string
          maxLength: 1000
          nullable: true
          example: "Milk, eggs, bread, and butter"
          description: Optional task description
        completed:
          type: boolean
          example: false
          description: Task completion status
        created_at:
          type: string
          format: date-time
          example: "2026-01-06T10:30:00Z"
          description: Task creation timestamp (UTC)
        updated_at:
          type: string
          format: date-time
          example: "2026-01-06T10:30:00Z"
          description: Last modification timestamp (UTC)

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
          minLength: 1
          example: "Buy groceries"
          description: Task title (required, 1-200 characters)
        description:
          type: string
          maxLength: 1000
          nullable: true
          example: "Milk, eggs, bread, and butter"
          description: Optional task description (max 1000 characters)

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
          minLength: 1
          example: "Buy groceries and vegetables"
          description: Updated task title (optional)
        description:
          type: string
          maxLength: 1000
          nullable: true
          example: "Milk, eggs, bread, butter, carrots, and lettuce"
          description: Updated task description (optional)

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Task not found"
          description: Human-readable error message
        detail:
          type: string
          example: "No task exists with ID 123"
          description: Additional error details

paths:
  /api/tasks:
    get:
      summary: List user's tasks
      description: Retrieve all tasks belonging to the authenticated user, optionally filtered by completion status
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
          description: Filter tasks by completion status
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              examples:
                all:
                  summary: All tasks
                  value:
                    - id: 1
                      user_id: "clx1234567890"
                      title: "Buy groceries"
                      description: "Milk, eggs, bread"
                      completed: false
                      created_at: "2026-01-06T10:30:00Z"
                      updated_at: "2026-01-06T10:30:00Z"
                    - id: 2
                      user_id: "clx1234567890"
                      title: "Finish project"
                      description: null
                      completed: true
                      created_at: "2026-01-05T09:00:00Z"
                      updated_at: "2026-01-06T11:00:00Z"
                pending:
                  summary: Pending tasks only
                  value:
                    - id: 1
                      user_id: "clx1234567890"
                      title: "Buy groceries"
                      description: "Milk, eggs, bread"
                      completed: false
                      created_at: "2026-01-06T10:30:00Z"
                      updated_at: "2026-01-06T10:30:00Z"
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid or expired token"

    post:
      summary: Create a new task
      description: Create a new task for the authenticated user
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "Buy groceries"
              description: "Milk, eggs, bread, and butter"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "clx1234567890"
                title: "Buy groceries"
                description: "Milk, eggs, bread, and butter"
                completed: false
                created_at: "2026-01-06T10:30:00Z"
                updated_at: "2026-01-06T10:30:00Z"
        '400':
          description: Bad Request - Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                emptyTitle:
                  summary: Empty title
                  value:
                    error: "Validation error"
                    detail: "Title cannot be empty"
                titleTooLong:
                  summary: Title too long
                  value:
                    error: "Validation error"
                    detail: "Title must be 200 characters or less"
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Invalid or expired token"

  /api/tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Task ID

    get:
      summary: Get a single task
      description: Retrieve a specific task by ID (must belong to authenticated user)
      operationId: getTask
      tags:
        - Tasks
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "clx1234567890"
                title: "Buy groceries"
                description: "Milk, eggs, bread, and butter"
                completed: false
                created_at: "2026-01-06T10:30:00Z"
                updated_at: "2026-01-06T10:30:00Z"
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Task belongs to different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Not authorized to access this task"
        '404':
          description: Not Found - Task doesn't exist or not owned by user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Task not found"

    put:
      summary: Update a task
      description: Update task title and/or description (must belong to authenticated user)
      operationId: updateTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            examples:
              updateBoth:
                summary: Update both title and description
                value:
                  title: "Buy groceries and vegetables"
                  description: "Milk, eggs, bread, butter, carrots, lettuce"
              updateTitle:
                summary: Update title only
                value:
                  title: "Buy groceries and vegetables"
              updateDescription:
                summary: Update description only
                value:
                  description: "Milk, eggs, bread, butter, carrots, lettuce"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "clx1234567890"
                title: "Buy groceries and vegetables"
                description: "Milk, eggs, bread, butter, carrots, lettuce"
                completed: false
                created_at: "2026-01-06T10:30:00Z"
                updated_at: "2026-01-06T14:45:00Z"
        '400':
          description: Bad Request - Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Task belongs to different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task doesn't exist or not owned by user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete a task
      description: Permanently delete a task (must belong to authenticated user)
      operationId: deleteTask
      tags:
        - Tasks
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Task belongs to different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task doesn't exist or not owned by user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/tasks/{id}/complete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
        description: Task ID

    patch:
      summary: Toggle task completion status
      description: Toggle task between completed and incomplete (must belong to authenticated user)
      operationId: toggleTaskComplete
      tags:
        - Tasks
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              examples:
                markComplete:
                  summary: Task marked as complete
                  value:
                    id: 1
                    user_id: "clx1234567890"
                    title: "Buy groceries"
                    description: "Milk, eggs, bread, and butter"
                    completed: true
                    created_at: "2026-01-06T10:30:00Z"
                    updated_at: "2026-01-06T15:00:00Z"
                markIncomplete:
                  summary: Task marked as incomplete
                  value:
                    id: 1
                    user_id: "clx1234567890"
                    title: "Buy groceries"
                    description: "Milk, eggs, bread, and butter"
                    completed: false
                    created_at: "2026-01-06T10:30:00Z"
                    updated_at: "2026-01-06T15:30:00Z"
        '401':
          description: Unauthorized - Invalid or missing JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Task belongs to different user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found - Task doesn't exist or not owned by user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

tags:
  - name: Tasks
    description: Task management operations
